# Generated by Django 3.1 on 2020-09-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='link',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
