# Generated by Django 3.1 on 2020-09-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_skill_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
